routes:
  /subscribe/: members/subscribe
  /signup/: members/signup
  /signin/: members/signin
  /account/: members/account
  /upgrade/: members/upgrade
  /resume/:
    template: resume
    data: page.resume
  /about/:
    template: about
    data: page.about

collections:
  /:
    permalink: /blog/{slug}/
    template: index
    filter: tag:hash-blog

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
# collections:
#   /blog/:
#     permalink: /blog/{slug}/
#     template: index
#     filter: tag:-blog
#     data: tag.blog
# routes:
# /:
#   data: page.home
#   template: home

# collections:
#   /blog/:
#     permalink: /blog/{slug}/
#     template: index

# Using Private tags
# /posts/:
#   permalink: /posts/{slug}/
#   template: index
#   filter: tag:hash-post
#   filter: tag:[iphone,ipad,mac]
