routes:
  /subscribe/: members/subscribe
  /signup/: members/signup
  /signin/: members/signin
  /account/: members/account
  /upgrade/: members/upgrade
  /about/:
    template: about
    data: page.about
  /resume/:
    template: resume
    data: page.resume
  /:
    controller: channel
    filter: "tag:-hash-course"
  # /courses/:
  #   controller: channel
  #   filter: "tag:hash-course"

collections:
  /blog/:
    permalink: /blog/{slug}/
    template: index
    filter: "tag:-hash-course+primary_tag:-newsletter"

  /newsletters/:
    permalink: /newsletter/{slug}/
    template: index
    filter: "primary_tag:newsletter"

  # Course example:
  # make tag url the same as the course
  # /intro-to-coding/:
  #   permalink: /course/{primary_tag}/{slug}/
  #   template: index
  #   filter: "tag:hash-course"
  #   order: asc

taxonomies:
  tag: /{slug}/
  author: /author/{slug}/
