routes:
  /subscribe/: members/subscribe
  /signup/: members/signup
  /signin/: members/signin
  /account/: members/account
  /upgrade/: members/upgrade
  /about/:
    template: about
    data: page.about
  /:
    controller: channel
    filter: "tag:-hash-course"

collections:
  /blog/:
    permalink: /blog/{slug}/
    template: index
    filter: "tag:-hash-course+primary_tag:-newsletter"

  /newsletters/:
    permalink: /newsletter/{slug}/
    template: index
    filter: "primary_tag:newsletter"

  /course/:
    permalink: /course/{primary_tag}/{slug}/
    template: index
    filter: "tag:hash-course"

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
